const baner = document.querySelector('.nav>ul');
const left = document.querySelector('.left1');
const right = document.querySelector('.right1');
const li = document.querySelectorAll('.nav>ul>li');
const ol = document.querySelector('.nav>ol')
const bannersImg = document.querySelectorAll('.nav>ul img')
const main = document.querySelector('main');
const recommend = document.querySelector('.recommend>ul');
const songsList = document.getElementById('songsList');
const find = document.querySelector('.cloud');
const previous = document.querySelector('.icon-previous2')
const next = document.querySelector('.icon-next2')
const slider = document.querySelector('.range')
const thumb = document.querySelector('.thumb');
const audio = document.getElementById('audio')
const player = document.querySelector('.play .icon-play3')
const playImg = document.querySelector('.song img') //封面
const playName = document.querySelector('.song .name') //歌名
const playSinger = document.querySelector('.song .singer') //歌手
const audioSrc = document.querySelector('.song audio') //播放源
const range = document.querySelector('.range')
const day = recommend.children[0].querySelector('span');
const day1 = songsList.querySelector('span');
const down = document.getElementById('list') //列表
const comments = document.getElementById('comments') //评论
const showList = document.querySelectorAll('.listNav span')
const slider1 = document.querySelector('.volume>div')
const sliderHeight = document.querySelector('.volume>div>div')
const thumb1 = document.querySelector('.volume>div>div>div');
const mine = document.querySelector('.myMusic');
const dropdown = document.querySelectorAll('button.head')
const show = document.querySelectorAll('.playList>ul')
const hotBox = document.querySelector('.start_search')
const search = document.querySelectorAll('.start_search li')
const oder = document.querySelectorAll('.start_search a>span')
const searchWord = document.querySelectorAll('.searchWord') //标题;
const score = document.querySelectorAll('.score'); //播放量
const content = document.querySelectorAll('.content'); //描述

const searchBox = document.querySelectorAll('.search input') //搜索框
const searchBtn = document.querySelectorAll('.search button')
const login = document.querySelector('.login')
const box = document.querySelector('.xbox')
const loginBox = document.querySelector('.loginBox')
const closeBox = document.querySelector('.close')
const lyricImg = document.querySelector('.playDetails .img img')
const listHead = document.querySelector('.listHead') //歌单列表页首
const songComments = document.querySelector('.songComments ul')
const playDetails = document.querySelector('.playDetails')
